
---
## Playbook to get system time and append it to backup files

- hosts: all
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true
 
 
- hosts: FortiGate
  connection: httpapi
  gather_facts: false
  
  collections: 
    - fortinet.fortios
  vars:
    vdom: "root"
    host: "194.168.4.5"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:
   - name: backup global
     fortios_system_config_backup_restore:
       config: "system config backup"
       host: "{{ host }}"
       vdom: "{{ vdom }}"
       backup: "yes"
       ssl_verify: False
       scope: "global or vdom"
       filename: "/root/backups/{{hostvars[inventory_hostname].DTG}}/{{inventory_hostname}}-{{hostvars[inventory_hostname].DTG}}-config.txt"

     
