# This playbook will connect to every device listed in the hosts file with the following command
#
# ansible-playbook pan_config_pull.yml -i host
#
# It will then  extract the running config from each devices and save them locally in ./config/
---

- name: Pull Configuration from Palo Alto Firewalls
  hosts: Palo_Alto
  gather_facts: no
  tasks:
    - name: Generate API Key
      connection: local
      check_mode: no
      uri:
        validate_certs: no
        url: 'https://{{ansible_host}}/api/?type=keygen&user={{ansible_ssh_user}}&password={{ansible_ssh_pass}}'
        return_content: yes
        method: GET
      register: key_string

    - name: Extract API Key from XML Output
      connection: local
      xml:
        xmlstring: '{{key_string.content}}'
        content: 'text'
        xpath: '/response/result/key'
      register: key_list

    - name: Backup configuration from PAN Equipement
      connection: local
      check_mode: no
      uri:
        validate_certs: no
        url: "https://{{ansible_host}}/api/?type=config&action=show&key={{key_list.matches[0].key}}"
        return_content: yes
        method: GET
      register: configuration_string
  
    - name: Remove XML Header and Save file in {{configs_dir}}
      connection: local
      check_mode: no
      copy:
        content: "{{configuration_string['content']  | regex_replace('<response.*<result>') | regex_replace('</result></response>')}}"
        dest: '/root/backups/paloalto/{{inventory_hostname}}.xml'

- hosts: SFTP_Server
  gather_facts: false
  
  tasks:  
  
    - name: Copy directory to remote host
      ansible.builtin.copy:
        src: /root/backups/paloalto
        dest: /var/sftp/backups/Palo_Alto_BD/
        remote_src: false

- hosts: localhost
  gather_facts: false

  tasks:
    - name: delete file
      ansible.builtin.file:
        path: /root/backups/paloalto/*
        state: absent
