---
## Playbook to get system time and append it to backup files

- hosts: all
  gather_facts: no
  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/Routers/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true

- hosts: Cisco_Routers
  gather_facts: false
  tasks:
   - name: Backup cisco routers
     cisco.ios.ios_command:
       commands: show run
     register : config
     
   - name: "Save output to  root/backups/"  
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/root/backups/Routers/{{  hostvars[inventory_hostname].DTG }}/{{ inventory_hostname }}-{{hostvars[inventory_hostname].DTG }}-config.txt" 

- hosts: SFTP_Server
  gather_facts: false
  
  tasks:  
  
    - name: Copy directory to remote host
      copy:
        src: /root/backups/Routers/
        dest: /var/sftp/Files/backups/Cisco_Routers_BD/
        remote_src: yes

- hosts: localhost
  gather_facts: false

  tasks:
    - name: delete file
      ansible.builtin.file:
        path: /root/backups/Routers
        state: absent
