---
## Playbook to get system time and append it to backup files

- hosts: all
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true
