---

- hosts: Linux_machines
  become: true
  tasks:
  
  - name: update repository index
    tags: update, Kali
    apt:
      update_cache: yes
    when: ansible_distribution in ["Kali", "Ubuntu"] 
    
  - name: install apache2 and php package
    tags: apache2, Kali
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Kali", "Ubuntu"] 
    

