---

- hosts: Linux_machines
  become: true
  tasks:
  
  - name: update repository index
    tags: update, Kali
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"] 
    
  - name: install apache2 and php package
    tags: apache2, Kali
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"] 
    
  - name: start apache2
    tags: apache, kali,apache2
    service:
      name: apache2
      state: started	
      enabled: yes
    
  - name: copy default html file for site
    tags: apache, apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      
     
      

