---
## Playbook to get system time and append it to backup files

- hosts: all
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true

- hosts: Dell_switches 

  gather_facts: false 
  
  tasks:
   - name: Backup DELL Switch
     dellemc.os10.os10_config: 
       backup: yes 
       backup_options: 
         dir_path: /root/backups/{{hostvars[inventory_hostname].DTG}}
         filename:  "{{inventory_hostname}}-{{hostvars[inventory_hostname].DTG}}-config.txt"
