---
## Playbook to get system time and append it to backup files

- name: Ensure required Ansible collections are installed
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Install Ansible collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml
      changed_when: false

- name: Backup configuration on Dell switches
  hosts: Dell_switches
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/Switches/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true

- name: Backup Dell EMC OS10 configuration
  hosts: Dell_switches
  gather_facts: no
  tasks:
   - name: Retrieve current config

     dellemc.os10.os10_command:
       commands:
         - show running-configuration
     register: running_config

   - name: Save config to file
     copy:
       content: "{{ running_config.stdout[0] }}"
       dest: "/root/backups/Switches/{{hostvars[inventory_hostname].DTG}}/{{inventory_hostname}}-{{hostvars[inventory_hostname].DTG}}-config.txt"

- hosts: SFTP_Server
  gather_facts: false
  
  tasks:  
  
    - name: Copy directory to remote host
      ansible.builtin.copy:
        src: /root/backups/Switches
        dest: /var/sftp/backups/Dell_Switches_BD/
        remote_src: false

- hosts: localhost
  gather_facts: false

  tasks:
    - name: delete file
      ansible.builtin.file:
        path: /root/backups/Switches/*
        state: absent
