---
## Playbook to get system time and append it to backup files

- hosts: Dell_switches
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/Switches/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true

- hosts: Dell_switches 

  gather_facts: false 
  
  tasks:
   - name: Backup DELL Switch
     dellemc.os10.os10_config: 
       backup: yes 
       backup_options: 
         dir_path: /root/backups/Switches/{{hostvars[inventory_hostname].DTG}}
         filename:  "{{inventory_hostname}}-{{hostvars[inventory_hostname].DTG}}-config.txt"

- hosts: SFTP_Server
  gather_facts: false
  
  tasks:  
  
    - name: Copy directory to remote host
      ansible.builtin.copy:
        src: /root/backups/Switches
        dest: /var/sftp/backups/Dell_Switches_BD/
        remote_src: false

- hosts: localhost
  gather_facts: false

  tasks:
    - name: delete file
      ansible.builtin.file:
        path: /root/backups/Switches/*
        state: absent
