- name: Push Configuration , Load & Commit configuration to Palo Alto Networks equipements
  hosts: SFTP_Server
  gather_facts: no

  tasks: 
    - name: Checking ssh connectivity
      connection: local
      wait_for: 
        host: '192.168.1.2'
        port: 22  
        timeout: 5

    - name: Download configuration file from SFTP server
      connection: local
      ansible.builtin.fetch:
        src: '/var/sftp/backups/Palo_Alto_BD/paloalto/PA.xml'
        dest: '/root/backups/paloalto/PA.xml'
        flat: yes
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_password }}'
        host: '{{ ansible_host }}'
        mode: '0666'
        
    - name: Push  configurations on each devices from the {{ configs_dir }} directory
      connection: local
      paloaltonetworks.panos.panos_import:
        validate_certs: no
        ip_address: '192.168.1.2'
        username: 'admin'
        password: '<F%F%ok>'
        file: '/root/backups/paloalto/PA.xml'
        category: "configuration"

    - name: Load configurations on each devices
      connection: local
      paloaltonetworks.panos.panos_loadcfg:
        ip_address: '192.168.1.2'
        username: 'admin'
        password: '<F%F%ok>'
        file: 'PA.xml'

    - name: Commit configuration on each devices
      connection: local
      paloaltonetworks.panos.panos_commit:
        ip_address: '192.168.1.2'
        username: 'admin'
        password: '<F%F%ok>'
