
---
## Playbook to get system time and append it to backup files

- hosts: all
  gather_facts: no

  tasks:
   - name: Get ansible date/time facts
     setup: 
       filter: "ansible_date_time"
       
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars[inventory_hostname].DTG}}
     file:
      path: /root/backups/{{ hostvars[inventory_hostname].DTG }}
      state: directory
  run_once: true


- hosts: F5_BIGIP
  connection: local
  gather_facts: no

  vars:
    f5Provider:
      server: "{{ mgmtAddr }}"
      server_port: 443
      user: "{{ f5User }}"
      password: "{{ f5Pwd }}"
      validate_certs: no
      transport: rest

  tasks:
    - name: Set archive name postfix data/time
      local_action: command date +%Y%m%d-%H%M%Z
      run_once: true
      register: date

    - name: Create UCS archive
      bigip_command:
        commands:
          - save sys ucs {{ inventory_hostname }}-{{ date['stdout'] }}
        provider: "{{f5Provider}}"
      delegate_to: localhost

    - name: Fetch UCS archive
      bigip_ucs_fetch:
        src: "{{ inventory_hostname }}-{{ date['stdout'] }}.ucs"
        dest: "tmp/{{ inventory_hostname }}-{{ date['stdout'] }}.ucs"
        provider: "{{f5Provider}}"
      delegate_to: localhost

- hosts: Cisco_Routers 
  gather_facts: false

  tasks:

   - name: Backup cisco routers
     cisco.ios.ios_command:
       commands: show run
     register : config
     
   - name: "Save output to  root/backups/"  
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/root/backups/{{  hostvars[inventory_hostname].DTG }}/{{ inventory_hostname }}-{{hostvars[inventory_hostname].DTG }}-config.txt" 


- hosts: Dell_switches 

  gather_facts: false 
  
  tasks:
   - name: Backup DELL Switch
     dellemc.os10.os10_config: 
       backup: yes 
       backup_options: 
         dir_path: /root/backups/{{hostvars[inventory_hostname].DTG}}
         filename:  "{{inventory_hostname}}-{{hostvars[inventory_hostname].DTG}}-config.txt"
      
    
   
  
 
  
